language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
